/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        /* ── Solaris 2026 neutral scale ──
           Calibrated so 400≈6:1 on 950 (dark body) and 600≈6:1 on 50 (light body).
           50=light-bg, 200=light-surface, 800=dark-surface, 900=dark-elevated, 950=dark-bg. */
        solaris: {
          50:  "rgb(var(--solaris-50) / <alpha-value>)",
          100: "rgb(var(--solaris-100) / <alpha-value>)",
          200: "rgb(var(--solaris-200) / <alpha-value>)",
          300: "rgb(var(--solaris-300) / <alpha-value>)",
          400: "rgb(var(--solaris-400) / <alpha-value>)",
          500: "rgb(var(--solaris-500) / <alpha-value>)",
          600: "rgb(var(--solaris-600) / <alpha-value>)",
          700: "rgb(var(--solaris-700) / <alpha-value>)",
          800: "rgb(var(--solaris-800) / <alpha-value>)",
          900: "rgb(var(--solaris-900) / <alpha-value>)",
          950: "rgb(var(--solaris-950) / <alpha-value>)",
        },
        /* ── Solaris 2026 accent families ──
           Canonical value at 500, tint up to 50, shade down to 900. */
        "solaris-blue": {
          50:  "rgb(var(--solaris-blue-50) / <alpha-value>)",
          100: "rgb(var(--solaris-blue-100) / <alpha-value>)",
          200: "rgb(var(--solaris-blue-200) / <alpha-value>)",
          300: "rgb(var(--solaris-blue-300) / <alpha-value>)",
          400: "rgb(var(--solaris-blue-400) / <alpha-value>)",
          500: "rgb(var(--solaris-blue-500) / <alpha-value>)",
          600: "rgb(var(--solaris-blue-600) / <alpha-value>)",
          700: "rgb(var(--solaris-blue-700) / <alpha-value>)",
          800: "rgb(var(--solaris-blue-800) / <alpha-value>)",
          900: "rgb(var(--solaris-blue-900) / <alpha-value>)",
        },
        "solaris-cyan": {
          50:  "rgb(var(--solaris-cyan-50) / <alpha-value>)",
          100: "rgb(var(--solaris-cyan-100) / <alpha-value>)",
          200: "rgb(var(--solaris-cyan-200) / <alpha-value>)",
          300: "rgb(var(--solaris-cyan-300) / <alpha-value>)",
          400: "rgb(var(--solaris-cyan-400) / <alpha-value>)",
          500: "rgb(var(--solaris-cyan-500) / <alpha-value>)",
          600: "rgb(var(--solaris-cyan-600) / <alpha-value>)",
          700: "rgb(var(--solaris-cyan-700) / <alpha-value>)",
          800: "rgb(var(--solaris-cyan-800) / <alpha-value>)",
          900: "rgb(var(--solaris-cyan-900) / <alpha-value>)",
        },
        "solaris-green": {
          50:  "rgb(var(--solaris-green-50) / <alpha-value>)",
          100: "rgb(var(--solaris-green-100) / <alpha-value>)",
          200: "rgb(var(--solaris-green-200) / <alpha-value>)",
          300: "rgb(var(--solaris-green-300) / <alpha-value>)",
          400: "rgb(var(--solaris-green-400) / <alpha-value>)",
          500: "rgb(var(--solaris-green-500) / <alpha-value>)",
          600: "rgb(var(--solaris-green-600) / <alpha-value>)",
          700: "rgb(var(--solaris-green-700) / <alpha-value>)",
          800: "rgb(var(--solaris-green-800) / <alpha-value>)",
          900: "rgb(var(--solaris-green-900) / <alpha-value>)",
        },
        "solaris-yellow": {
          50:  "rgb(var(--solaris-yellow-50) / <alpha-value>)",
          100: "rgb(var(--solaris-yellow-100) / <alpha-value>)",
          200: "rgb(var(--solaris-yellow-200) / <alpha-value>)",
          300: "rgb(var(--solaris-yellow-300) / <alpha-value>)",
          400: "rgb(var(--solaris-yellow-400) / <alpha-value>)",
          500: "rgb(var(--solaris-yellow-500) / <alpha-value>)",
          600: "rgb(var(--solaris-yellow-600) / <alpha-value>)",
          700: "rgb(var(--solaris-yellow-700) / <alpha-value>)",
          800: "rgb(var(--solaris-yellow-800) / <alpha-value>)",
          900: "rgb(var(--solaris-yellow-900) / <alpha-value>)",
        },
        "solaris-orange": {
          50:  "rgb(var(--solaris-orange-50) / <alpha-value>)",
          100: "rgb(var(--solaris-orange-100) / <alpha-value>)",
          200: "rgb(var(--solaris-orange-200) / <alpha-value>)",
          300: "rgb(var(--solaris-orange-300) / <alpha-value>)",
          400: "rgb(var(--solaris-orange-400) / <alpha-value>)",
          500: "rgb(var(--solaris-orange-500) / <alpha-value>)",
          600: "rgb(var(--solaris-orange-600) / <alpha-value>)",
          700: "rgb(var(--solaris-orange-700) / <alpha-value>)",
          800: "rgb(var(--solaris-orange-800) / <alpha-value>)",
          900: "rgb(var(--solaris-orange-900) / <alpha-value>)",
        },
        "solaris-red": {
          50:  "rgb(var(--solaris-red-50) / <alpha-value>)",
          100: "rgb(var(--solaris-red-100) / <alpha-value>)",
          200: "rgb(var(--solaris-red-200) / <alpha-value>)",
          300: "rgb(var(--solaris-red-300) / <alpha-value>)",
          400: "rgb(var(--solaris-red-400) / <alpha-value>)",
          500: "rgb(var(--solaris-red-500) / <alpha-value>)",
          600: "rgb(var(--solaris-red-600) / <alpha-value>)",
          700: "rgb(var(--solaris-red-700) / <alpha-value>)",
          800: "rgb(var(--solaris-red-800) / <alpha-value>)",
          900: "rgb(var(--solaris-red-900) / <alpha-value>)",
        },
        "solaris-violet": {
          50:  "rgb(var(--solaris-violet-50) / <alpha-value>)",
          100: "rgb(var(--solaris-violet-100) / <alpha-value>)",
          200: "rgb(var(--solaris-violet-200) / <alpha-value>)",
          300: "rgb(var(--solaris-violet-300) / <alpha-value>)",
          400: "rgb(var(--solaris-violet-400) / <alpha-value>)",
          500: "rgb(var(--solaris-violet-500) / <alpha-value>)",
          600: "rgb(var(--solaris-violet-600) / <alpha-value>)",
          700: "rgb(var(--solaris-violet-700) / <alpha-value>)",
          800: "rgb(var(--solaris-violet-800) / <alpha-value>)",
          900: "rgb(var(--solaris-violet-900) / <alpha-value>)",
        },
        "solaris-magenta": {
          50:  "rgb(var(--solaris-magenta-50) / <alpha-value>)",
          100: "rgb(var(--solaris-magenta-100) / <alpha-value>)",
          200: "rgb(var(--solaris-magenta-200) / <alpha-value>)",
          300: "rgb(var(--solaris-magenta-300) / <alpha-value>)",
          400: "rgb(var(--solaris-magenta-400) / <alpha-value>)",
          500: "rgb(var(--solaris-magenta-500) / <alpha-value>)",
          600: "rgb(var(--solaris-magenta-600) / <alpha-value>)",
          700: "rgb(var(--solaris-magenta-700) / <alpha-value>)",
          800: "rgb(var(--solaris-magenta-800) / <alpha-value>)",
          900: "rgb(var(--solaris-magenta-900) / <alpha-value>)",
        },
      },
    },
  },
  plugins: [],
};
